Add modification detail fields
Issues:
- Tested on my end and EntityFramework doesnt recognize the new fields, throws this error:
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while saving entities that do not expose foreign key properties for their relationships. The EntityEntries property will return null because a single entity cannot be identified as the source of the exception. Handling of exceptions while saving can be made easier by exposing foreign key properties in your entity types. See the InnerException for details. ---> System.Data.Entity.Core.UpdateException: A relationship from the 'Suggestion_ModifiedBy' AssociationSet is in the 'Deleted' state. Given multiplicity constraints, a corresponding 'Suggestion_ModifiedBy_Source' must also in the 'Deleted' state.

Need a 2nd tester to try out if can work or not. If it doesn't, need your help to troubleshoot wz.